services:
  server:
    image: ts-demo:1.0.0
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
  redis:
    image: redis:7
    ports:
      - "16379:6397"
    volumes:
      - "redis-data:/data"
volumes:
  redis-data:
